server:
  applicationConnectors:
    - type: http
      port: 8085
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/todo_db
  user: postgres
  password: postgres
